export const musicVibeMessage: string[] = [
    "Let's groove together! ♪┏(・o･)┛♪",
    "Time to dance! (〜￣▽￣)〜",
    "Feel the rhythm! ~(^з^)-♪",
    "Music magic in the air! ♪(┌・。・)┌",
    "Dance party mode activated! ╮(╯▽╰)╭",
    "Turning up the volume! ⁽⁽◝( •௰• )◜⁾⁾",
    "Jamming to this tune! (＾▽＾)/",
    "Music makes everything better! ♪(๑ᴖ◡ᴖ๑)♪",
    "Let the music take control! (‾▽‾)",
    "Dancing in my chair! ♪(๑ᴖ◡ᴖ๑)♪",
    "Can't stop the groove! (｢• ω •)｢",
    "Music to my ears! ♬♫♪◖(● o ●)◗♪♫♬",
    "Dancing with the beats! ＼(ﾟｰﾟ＼)",
    "Time to shuffle! (‾∇‾)",
    "Vibing with the rhythm! (✧ω✧)",
    "Music makes me move! ♪(┌・。・)┌",
    "Getting into the groove! (˘▾˘)",
    "Dancing like nobody's watching! (〜^∇^)〜",
    "Feeling the music flow! ヾ(⌐■_■)ノ♪",
    "Let's get this party started! └(^o^)┐",
]